services:
  postgres:
    image: postgres:15
    container_name: vod_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: vodSystem
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    container_name: vod_backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      FRONTEND_URL: http://localhost
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vod_frontend
    env_file:
      - .env
    environment:
      VITE_API_URL: ""
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    depends_on:
      - backend
    ports:
      - "1935:1935"
    restart: unless-stopped

  rtmp:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: vod_rtmp
    ports:
      - "1935:1935"
    volumes:
      - ${STREAM_DATA}:/stream
    restart: unless-stopped