services:

  postgres:
    image: postgres:15
    container_name: vod_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: vodSystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    container_name: vod_backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vod_frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  postgres_data: