spring.docker.compose.file=docker-compose.dev.yml

media.temp.inputs=./videos/inputs
media.temp.outputs=./videos/outputs
media.users=${MEDIA_DATA}
media.streams=${STREAM_DATA}

logging.level.com.ddf.vodsystem=DEBUG